kind: Kustomization
metadata:
  name: dynamo
resources:
  - dynamodb.yaml
secretGenerator:
  - name: dynamo-secret
    files:
      - AWS_ACCESS_KEY_ID=secrets/access-key
      - AWS_SECRET_ACCESS_KEY=secrets/secret-key
